name: "Lint Ansible roles"

on:
  push:
    branches-ignore:
      - main

jobs:
  ansible-lint:
    name: "Ansible Lint"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Lint Ansible Playbook"
      uses: ansible/ansible-lint-action@v6.0.2
      with:
        path: ./
